version: '3'
services:
  zookeeper:
    container_name: myzookeeper
    image: zookeeper
    ports:
      - "2181:2181"
    restart: always

  kafka:
    container_name: mykafkaserver
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      #- KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    links:
      - zookeeper

  spark:
    container_name: myspark
    image: bitnami/spark
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./:/app
    links:
      - kafka
      - zookeeper
    user: root
    command: bash -c "
      useradd -ms /bin/bash newuser &&
      mkdir -p /opt/bitnami/.cache/pip &&
      chown -R newuser:newuser /opt/bitnami/.cache/pip &&
      su newuser -c '
      /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master
      '
     "